# Generated by Django 5.2.6 on 2025-09-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fileType", models.CharField(max_length=255)),
                ("fileSize", models.IntegerField()),
                ("fileName", models.TextField()),
                ("uri", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobTitle", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("jobType", models.CharField(max_length=255)),
                ("salary", models.CharField(max_length=255)),
                ("companySize", models.CharField(max_length=255)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("jobDescription", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company_logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings_logo",
                        to="SignedBackend.mediaitem",
                    ),
                ),
                (
                    "media_items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_postings",
                        to="SignedBackend.mediaitem",
                    ),
                ),
            ],
        ),
    ]
