# Generated by Django 5.2.6 on 2025-09-29 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SignedBackend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobposting",
            old_name="companySize",
            new_name="company_size",
        ),
        migrations.RenameField(
            model_name="jobposting",
            old_name="jobDescription",
            new_name="job_description",
        ),
        migrations.RenameField(
            model_name="jobposting",
            old_name="jobTitle",
            new_name="job_title",
        ),
        migrations.RenameField(
            model_name="mediaitem",
            old_name="fileName",
            new_name="download_link",
        ),
        migrations.RenameField(
            model_name="mediaitem",
            old_name="uri",
            new_name="file_name",
        ),
        migrations.RenameField(
            model_name="mediaitem",
            old_name="fileSize",
            new_name="file_size",
        ),
        migrations.RenameField(
            model_name="mediaitem",
            old_name="fileType",
            new_name="file_type",
        ),
    ]
