# Generated by Django 5.2.6 on 2025-09-29 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SignedBackend", "0002_rename_companysize_jobposting_company_size_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobposting",
            old_name="jobType",
            new_name="job_type",
        ),
    ]
