# Generated by Django 5.2.6 on 2025-09-29 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SignedBackend", "0003_rename_jobtype_jobposting_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="company_logo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_postings_logo",
                to="SignedBackend.mediaitem",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="company_size",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="job_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="media_items",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="job_postings",
                to="SignedBackend.mediaitem",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="salary",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
