# Generated by Django 5.2.6 on 2025-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SignedBackend", "0005_verificationcode_alter_jobposting_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="media_items",
            field=models.ManyToManyField(
                blank=True, related_name="job_postings", to="SignedBackend.mediaitem"
            ),
        ),
    ]
