# Generated by Django 5.2.6 on 2025-10-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SignedBackend", "0006_alter_jobposting_media_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="user",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="type",
            field=models.CharField(
                choices=[("EM", "Email"), ("PH", "Phone")], default="EM", max_length=2
            ),
        ),
    ]
