# Generated by Django 5.2.6 on 2025-10-05 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SignedBackend", "0007_verificationcode_user_alter_verificationcode_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="type",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("PHONE", "Phone")],
                default="EMAIL",
                max_length=5,
            ),
        ),
    ]
