# Generated by Django 5.2.6 on 2025-10-09 23:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_profiles/'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='applicant_resumes/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='employer_profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
