# Generated by Django 5.2.6 on 2025-12-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='followed_companies',
        ),
    ]
