# Generated by Django 5.2.6 on 2025-11-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='num_rejects',
            field=models.IntegerField(default=0),
        ),
    ]
