# Generated by Django 5.2.6 on 2025-10-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
