# Generated by Django 5.2.6 on 2025-11-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='personality_preferences',
            field=models.ManyToManyField(blank=True, to='accounts.personalitytype'),
        ),
    ]
