# Generated by Django 5.2.6 on 2025-11-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicantprofile_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='bookmarked_jobs',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by_applicants', to='accounts.jobposting'),
        ),
    ]
