# Generated by Django 5.2.6 on 2025-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_applicantprofile_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
