# Generated by Django 5.2.6 on 2025-10-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_jobposting_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='vector_embedding',
            field=models.JSONField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
    ]
