# Generated by Django 5.2.6 on 2025-12-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_applicantprofile_followed_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='followed_companies',
            field=models.ManyToManyField(blank=True, related_name='followers', to='accounts.company'),
        ),
    ]
