# Generated by Django 5.2.6 on 2025-10-07 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_applicantprofile_resume_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("file_name", models.TextField()),
                ("download_link", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("PHONE", "Phone")],
                        default="EMAIL",
                        max_length=5,
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("user", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("job_type", models.CharField(max_length=255)),
                ("salary", models.CharField(max_length=255, null=True)),
                ("company_size", models.CharField(max_length=255, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("job_description", models.TextField(null=True)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company_logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings_logo",
                        to="accounts.mediaitem",
                    ),
                ),
                (
                    "media_items",
                    models.ManyToManyField(
                        blank=True, related_name="job_postings", to="accounts.mediaitem"
                    ),
                ),
            ],
        ),
    ]
