# Generated by Django 5.2.6 on 2025-10-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_applicantprofile_vector_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='vector_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
