# Generated by Django 5.2.6 on 2025-12-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_applicantprofile_bookmarked_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
    ]
