# Generated by Django 5.2.6 on 2025-10-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_applicantprofile_vector_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='vector_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
