# Generated by Django 5.2.6 on 2025-10-08 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_mediaitem_verificationcode_jobposting"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="posted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_postings",
                to="accounts.employerprofile",
            ),
        ),
    ]
