# Generated by Django 5.2.6 on 2025-11-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobposting_vector_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
