# Generated by Django 5.2.6 on 2025-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_jobposting_vector_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="applicants",
            field=models.ManyToManyField(
                blank=True, related_name="applied_jobs", to="accounts.applicantprofile"
            ),
        ),
    ]
