# Generated by Django 5.2.6 on 2025-11-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_applicantprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
